# Generated by Django 3.2.3 on 2021-06-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('preco', models.IntegerField()),
                ('descricao', models.CharField(max_length=512)),
                ('url_img', models.CharField(max_length=255)),
            ],
        ),
    ]
